### ISSUE TITLE
Not able to Delete domain from the Domain list

### ISSUE THREAD

**Issue by satya876** [McLive/DjangoPowerDNS#8]
Hello,

When trying to delete Domain, from the domain list. We are not able to delete. When selecting the "Delete" button nothing happening. Also when trying to delete records, its taking too long and page gets struck unless we refresh it manually.

Kindly suggest solution.

Thank You !!

![image](https://user-images.githubusercontent.com/18626620/47667571-53c48700-dbcc-11e8-96d3-5db24e128dbc.png)

**Comment by McLive** [comment]
Looks like you have some issues with the javascript librarys used. Do you see any errors in your browsers DEV console?

**Comment by justabaka** [comment]
Javascript library (sweetalert) is missing due to a massive .gitignore ruleset. I've dealt with the problem and updated the library to v 2.x. Also the frontend code had to be adjusted as well. Please take a look: 

https://github.com/justabaka/DjangoPowerDNS/commit/4fd83564f4a07102c88605e4017b01a9b279a4a8
https://github.com/justabaka/DjangoPowerDNS/commit/b11391013582004c6951db70cad10d98b868872a

P.S. Maybe it's easier to use a library CDN or supply only the compiled (/dist/) version since the library is not shipped as a git submodule and there are no building instructions for the end users.

**Comment by McLive** [comment]
Thanks to @justabaka for pointing this out. :)
